### ISSUE TITLE
Convert libcommon_em.so into a static library

### ISSUE THREAD

**Issue by hcneema** [Xilinx/XRT#101]
We need to do the following 

Currently we have
SJBRD2:/opt/xilinx/xrt>tree lib
lib
├── libcommon_em.so
├── libcpu_em.so
├── libhw_em.so
├── libxilinxopencl.so -> libxilinxopencl.so.2
├── libxilinxopencl.so.2 -> libxilinxopencl.so.2.1.0
├── libxilinxopencl.so.2.1.0
├── libxrtcore.so -> libxrtcore.so.2
├── libxrtcore.so.2 -> libxrtcore.so.2.1.0
└── libxrtcore.so.2.1.0

1. Rename libhw_em.so to libxrt_hwem.so
2. Rename libcpu_em.so to libxrt_swem.so
3. Remove libcommon_em.so -> create a static library(.a) and embed it within libxrt_swem.so and libxrt_hwem.so
4. Add .soname versioning.
5. Remove XILINX_SDX dependency  for running the testcase(currently it requires it to be set to any junk value).
6. Make sure emulation flows work off the changes.

**Comment by stsoe** [comment]
No longer relevant.
