### ISSUE TITLE
xbutil crash on flashing

### ISSUE THREAD

**Issue by hackwa** [Xilinx/XRT#1263]
xbutil flash -a xilinx_u200_xdma_201830_1
XBFLASH -- Xilinx Card Flash Utility
Probing card[0]: Shell on FPGA needs updating
Shell on below card(s) will be updated:
Card [0]
Are you sure you wish to proceed? [y/n]
y
Updating shell on card[0]
INFO: ***Found 701 ELA Records
Idcode byte[0] ff
Idcode byte[1] 20
Idcode byte[2] bb
Idcode byte[3] 21
Idcode byte[4] 10
Enabled bitstream guard. Bitstream will not be loaded until flashing is finished.
Erasing flash........................z...........
Programming flashxbutil: /root/hackwad/XRT/src/runtime_src/driver/xclng/tools/xbmgmt/xspi.cpp:1359: int XSPI_Flasher::programXSpi(std::istream&, const XSPI_Flasher::ELARecord&): Assertion `(address + da
taLen - (record.mStartAddress & 0xFFFF)) == static_cast<unsigned int>((pageIndex +1)*128)' failed.
Aborted (core dumped)

**Comment by maxzhen** [comment]
@cellery , do you know anything about this assertion?

**Comment by cellery** [comment]
This assertion fails when you try to flash with debug XRT build and not release. No one ever updated the assert statement to fix the check.

**Comment by keryell** [comment]
@sonals who is the right person to move on this?
I just spent a couple hours on this again and that is a shame. :-(
Is there any Continuous Integration made on this?
Who is in charge of this CI inside Xilinx?

**Comment by maxzhen** [comment]
Did you try latest master branch? Should've been fixed there.

**Comment by keryell** [comment]
The problem is that I do not know if I can use the `master` branch or not. Is it supposed to work with the SDx 2019.1 public version? I am going to create an issue on it.
For now I was trying only officially available stuff...

**Comment by maxzhen** [comment]
the master should work. if not, it's a bug of highest priority.

**Comment by hackwa** [comment]
Awesome! thanks for confirming @keryell. I do not know what the specific commit is for cherry picking. Maybe @maxzhen  or @cellery could help?

**Comment by maxzhen** [comment]
The change is just to remove the assertion. Can't do cherry-pick since it's part of a big change which can't be backported to 2019.1. For 2019.1, please use release version of xbutil flash.
