### ISSUE TITLE
Typo in thrown error in memory.cpp

### ISSUE THREAD

**Issue by agozillon** [Xilinx/XRT#1420]
The error thrown on line 98 of memory.cpp (https://github.com/Xilinx/XRT/blob/master/src/runtime_src/xocl/api/detail/memory.cpp#L98) appears to have a typo:

"host_ptr may not be nullptr when CL_ME_EXT_PTR_XILINX is specified" 
->
"host_ptr may not be nullptr when CL_MEM_EXT_PTR_XILINX is specified" 

Not a particularly big issue.. but thought I'd point it out in any case on the off chance its not been noticed yet.

**Comment by stsoe** [comment]
Thank you. Fixed in #1421
