### ISSUE TITLE
clEnqueueUnmapMemObject event_wait_list clarification 

### ISSUE THREAD

**Issue by agozillon** [Xilinx/XRT#1425]
Back again so soon, sorry! In this case I believe its a bug, but I could be misinterpreting or misunderstanding something.

In the `clEnqueueUnmapMemObject` call there is a check to see if a mapped ptr is a valid ptr ([here](https://github.com/Xilinx/XRT/blob/master/src/runtime_src/xocl/api/clEnqueueUnmapMemObject.cpp#L64)) i.e. has already been mapped to the device via a `clEnqueueMapBuffer` call.

This of course makes sense, however this check seems to occur before dependent events from the event wait list are processed/scheduled. Which I have found to be a bit of a problem, for example what if one of the events in my wait list happens to be the `clEnqueueMapBuffer` call that I wish to `clEnqueueUnmapMemObject` eventually after a series of intermediate events? At the moment it will trigger the error I linked above, which feels a little odd as if the `clEnqueueMapBuffer` is one of the events to be waited on before `clEnqueueUnmapMemObject` is executed then it should never trigger this error unless the `clEnqueueMapBuffer` call is actually invalid.

Perhaps this is API misuse and I am wrong however, my apologies in that case! I also couldn't work out a great title for this issue, so if it needs to be renamed please do so!

**Comment by keryell** [comment]
@sonals who is the right person to answer this?
