### ISSUE TITLE
Device fails to program if a previously downloaded XCLBIN didn't run any kernels

### ISSUE THREAD

**Issue by swilson-xlnx** [Xilinx/XRT#1453]
If we an XCLBIN is downloaded, and several OpenCL objects are created, **but a kernel is not run**, future downloads fail.

Attached is some code to illustrate the problem:
[main.cpp.txt](https://github.com/Xilinx/XRT/files/3198797/main.cpp.txt)

In main.cpp you will see several calls to a test function:

Test(xclbinPath, true);
Test(xclbinPath, true);
Test(xclbinPath, false);
Test(xclbinPath, true);
Test(xclbinPath, true);
Test(xclbinPath, true);
Test(xclbinPath, true);

The bool parameter determines whether a call to **enqueueTask** is made.

NOTE that the **THIRD** call has it set to **false**.

This results in the following output:

_Found Platform_
_Platform Name: Xilinx
INFO: Importing kernel_mc_u250_hw.xclbin
Loading: 'kernel_mc_u250_hw.xclbin'
Call Number = 1, cl_retval = 0_

_Found Platform
Platform Name: Xilinx
INFO: Importing kernel_mc_u250_hw.xclbin
Loading: 'kernel_mc_u250_hw.xclbin'
Call Number = 2, cl_retval = 0_

_Found Platform
Platform Name: Xilinx
INFO: Importing kernel_mc_u250_hw.xclbin
Loading: 'kernel_mc_u250_hw.xclbin'
Call Number = 3, cl_retval = 0_

_Found Platform
Platform Name: Xilinx
INFO: Importing kernel_mc_u250_hw.xclbin
Loading: 'kernel_mc_u250_hw.xclbin'
Call Number = 4, cl_retval = 0_

_Found Platform
Platform Name: Xilinx
INFO: Importing kernel_mc_u250_hw.xclbin
Loading: 'kernel_mc_u250_hw.xclbin'
**ERROR: some device is already programmed**
**Call Number = 5, cl_retval = -5**_

_Found Platform
Platform Name: Xilinx
INFO: Importing kernel_mc_u250_hw.xclbin
Loading: 'kernel_mc_u250_hw.xclbin'
**ERROR: some device is already programmed**
**Call Number = 6, cl_retval = -5**_

_Found Platform
Platform Name: Xilinx
INFO: Importing kernel_mc_u250_hw.xclbin
Loading: 'kernel_mc_u250_hw.xclbin'
**ERROR: some device is already programmed**
**Call Number = 7, cl_retval = -5**_

It is the **THIRD** call where we don't execute the kernel.  Interestingly, the **FOURTH** call executes OK, but it is the **FIFTH** call onwards that fails.

If you change the bool parameter of the **THIRD** call to true, all 7 calls work OK.

**Comment by stsoe** [comment]
I cannot reproduce this with a similar separate example.
If you can show this with a complete example, then please file a CR or a new issue with all data.
