### ISSUE TITLE
Document the versions of the tools compatible with the runtime

### ISSUE THREAD

**Issue by keryell** [Xilinx/XRT#1515]
It is not clear right now which branch to use with which version of the various Xilinx tools.
Is this just related with the XRT version (2.2, 2.3...) and can be simplified at this level?
For example what are the XRT branches compatible with SDAccel 2019.1?

This issue came out from https://github.com/Xilinx/XRT/issues/1263 and is also somehow related to https://github.com/Xilinx/XRT/issues/1136

**Comment by keryell** [comment]
@uday610 I've been told you are the guy to know and document this somewhere. :-)

**Comment by uday610** [comment]
Hello @keryell , the XRT git branch generally says which SDx version it is compatible with
