### ISSUE TITLE
xrtdeps.sh fails to install EPEL on Centos 7.5

### ISSUE THREAD

**Issue by gareth-xlnx** [Xilinx/XRT#1544]
On branch 2019.1 of the repo, if I try to use `xrtdeps.sh` to install prerequisites on a fresh install of CentOS 7.5, EPEL fails to install:

```
No package epel-release available.
Error: Nothing to do
```

I need to manually run the line listed against RHEL :
```
 $SUDO yum install http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
```
in order to add the EPEL repository and allow the installation of cmake3.

Should the CentOS branch of the conditional just be the same as the RHEL one?

**Comment by uday610** [comment]
7.5 is no longer supported
