### ISSUE TITLE
unable to perform ./build.sh

### ISSUE THREAD

**Issue by durgabhavaniv** [Xilinx/XRT#1606]
cd XRT/build
./build.sh

Above step throwing the following error as below:
/usr/bin/cmake3: /opt/Xilinx/SDx/2018.2/lib/lnx64.o/libxml2.so.2: no version information available (required by /lib64/libarchive.so.13)

**Comment by keryell** [comment]
You should have a clean environment with the required packages installed/compiled.
So, *do not* source some configuration files from Xilinx `/opt/Xilinx/...` or `/proj/xbuilds/...` otherwise you can get some random pieces of bits...

**Comment by durgabhavaniv** [comment]
With out sourcing I got same issue as below:

[ 45%] Linking CXX executable xclbintest
/usr/bin/cmake3: /opt/Xilinx/SDx/2018.2/lib/lnx64.o/libxml2.so.2: no version information available (required by /lib64/libarchive.so.13)
[ 45%] Built target xclbinutil
/usr/bin/cmake3: /opt/Xilinx/SDx/2018.2/lib/lnx64.o/libxml2.so.2: no version information available (required by /lib64/libarchive.so.13)
[ 45%] Built target xclbintest
make: *** [all] Error 2

**Comment by keryell** [comment]
Curious...
Where does this `/opt/Xilinx/SDx/2018.2` come from then?
What is the output of
```
printenv | grep /opt/Xilinx/SDx
```
for example?

What is your OS? What is this `cmake3`?

**Comment by uday610** [comment]
There is no response from the reporter. So closing this
