### ISSUE TITLE
Add check for ingested xclbin (2018.3)

### ISSUE THREAD

**Issue by rradjabi** [Xilinx/XRT#1632]
In xrt-aws, if a user passes an xclbin that has not gone through ingestion, a segfault will occur since an ingested awsxclbin with bitstream stripped is expected. 

A simple fix can be put in userspace https://github.com/Xilinx/XRT/blob/96d6e282f215ca59570ce15c1c9b2dba8f55e8a1/src/runtime_src/driver/xclng/xrt/user_aws/shim.cpp#L153. When an xclbin is passed in that is too large, it can be assumed that it has not been stripped of it's bitstream, and thus is an invalid awsxclbin. Display a message indicating this and error out.

**Comment by rradjabi** [comment]
@xuhz any fix for this yet?

**Comment by xuhz** [comment]
fixed
