### ISSUE TITLE
Add check for ingested xclbin on AWS (2019.1)

### ISSUE THREAD

**Issue by rradjabi** [Xilinx/XRT#1633]
A segfault is reached if a user passes an xclbin that has not gone through ingestion. Amazon is requesting a proper fix for this in 2019.1. The same issue is experienced in 2018.3, for which an easy userspace fix was suggested (#1632). You may want to apply a more sophisticated, data-driven fix.

**Comment by rradjabi** [comment]
@xuhz any fix for this yet?

**Comment by xuhz** [comment]
fixed
