### ISSUE TITLE
Validate kernel test failed_Failed to find any debug IP_Xbutil mem failed - POWER9_ubuntu 18.04 PPC64LE

### ISSUE THREAD

**Issue by dexty007** [Xilinx/XRT#1654]
https://forums.xilinx.com/t5/Alveo-Data-Center-Accelerator/Issue-installing-XRT-and-Deployment-Shell-in-Power9/td-p/994207

I've opened an issue on community forum regarding this, it needs to be solved in the present version, there are some precompiled x86 libraries which need to be cleaned I guess and add support for POWER9 with ubuntu 18.04 PPC64LE

![validate_kernal_failed](https://user-images.githubusercontent.com/33428852/61169596-244c8380-a57d-11e9-93f0-3a176ee54289.jpeg)
![xbutil](https://user-images.githubusercontent.com/33428852/61169597-24e51a00-a57d-11e9-8bb3-eb4baa141f85.jpeg)

**Comment by uday610** [comment]
Should be supported today...
