### ISSUE TITLE
Calling xclGetSectionInfo when XCLBIN has not been programmed yet results in segfault.

### ISSUE THREAD

**Issue by swilson-xlnx** [Xilinx/XRT#2425]
Following a cold reboot of our server (which obviously results in the FPGA being blank), a call to **xclGetSectionInfo** to query the IP LAYOUT (which should be empty) results in a **segmentation fault.**

**Comment by maxzhen** [comment]
please file a CR with source of the host code and core dump. we can take a look at CR.
