### ISSUE TITLE
Library Error: /usr/lib/libxdp.so.2: undefined symbol: 

### ISSUE THREAD

**Issue by hango-hango** [Xilinx/XRT#2462]
When I try to build a XRT runtime on my zynq7100 board, I get a runtime error as follows. I need help for the reason of this problem, thanks.

`root@hz100ocl:/mnt# ./ocl.exe kernel.xclbin 
XRT build version: 2.3.0
Build hash: 874c2cb41f63e68fc41b4e2d62bf6695393e7d54
Build date: 2019-11-19 07:39:24
Git branch: master
PID: 1219
UID: 0
[Tue Nov 19 08:00:36 2019]
HOST: hz100ocl
EXE: /mnt/ocl.exe
[XRT] ERROR: Failed to open XDP library '/usr/lib/liboclxdp.so'
/usr/lib/libxdp.so.2: undefined symbol: _ZN8xrt_core6system12get_xrt_infoERN5boost13property_tree11basic_ptreeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_St4lessIS9_EEE
Error: Unable to find Target Device [XRT] ERROR: device is nullptr`

**Comment by uday610** [comment]
this should not be an issue now, closing.
