### ISSUE TITLE
How do I verify that XRT works?

### ISSUE THREAD

**Issue by Vae1997** [Xilinx/XRT#2566]
Hello!
I booted from the SD card and started Ubuntu16.04 on the ZCU102 board.
Then configure XRT via Petalinux and generate zocl.ko and /opt/xilinx/xrt/.
Finally I just copied all the generated files to Ubuntu.
What should I do next to make sure XRT is already working in the system?
Thanks a lot.

**Comment by uday610** [comment]
Possibly running a small testcase, there is no "xbutil validate" for embedded platform. Already discussed with @chvamshi-xilinx . Closing this
