### ISSUE TITLE
System freezes when running add1_zgem.cpp

### ISSUE THREAD

**Issue by Vae1997** [Xilinx/XRT#2624]
When I run the XRT / src / runtime_src / driver / zynq / test / add1_zgem.cpp file, the system interface becomes unresponsive and the mouse cannot move.
In the current directory, the effect of add1_zgem_64.cpp is the same.
But when I execute zgem1.c, the output is as follows:
Note: zgem1 is compiled by g ++ zgem1.c -o zgem1
root @ zcu102: ~ / XRT-2018.3 / src / runtime_src / driver / zynq / test # ./zgem1
CREATE
result = 0
Handle 1
result = 0
Handle 2
result = 0
Handle 3
INFO
result = 0
Handle 1
Size 4096
Physical 3fcc9000
result = 0
Handle 2
Size 8192
Physical 3fce4000
result = 0
Handle 3
Size 8192
Physical 3fce6000
PWRITE
result = 0
result = 0
result = 0
PREAD / COMPARE
result = 0
result = 0
result = 0
result = 0
result = 0
result = 0
MMAP
result = 0
Handle 1
Offset 100000000
Pointer 0x7f949ef000
result = 0
Handle 2
Offset 100001000
Pointer 0x7f949ed000
result = 0
Handle 3
Offset 100003000
Pointer 0x7f949eb000
MMAP / COMPARE
result = 0
result = 0
result = 0
MMAP / UPDATE
MUNMAP
result = 0
result = 0
result = 0
PREAD / COMPARE
result = 0
result = 0
result = 0
result = 0
result = 0
result = 0
CLOSE
result = 0
result = 0
result = 0
result = 0
root @ zcu102: ~ / XRT-2018.3 / src / runtime_src / driver / zynq / test #
What should I do to make the other two tests run successfully?Thanks.

**Comment by uday610** [comment]
this testcase no longer part of XRT repo
