### ISSUE TITLE
shim-profile.h seems to be missing.. XRT build broken?

### ISSUE THREAD

**Issue by tschesnok** [Xilinx/XRT#2656]
shim_hwem.cpp references "shim-profile.h" which is no longer in the repository???

When I run ~/XRT/src/runtime_src/tools/scripts/peta_build.sh ~/PetaBuilds/xsa_build/zcu104_revmin/zcu104_revmin.xsa
I get: 

 /home/andrew/XRT/src/runtime_src/core/edge/hw_em/shim_hwem.cpp:24:10: fatal error: shim-profile.h: No such file or directory
|  #include "shim-profile.h"
|           ^~~~~~~~~~~~~~~~
| compilation terminated.

I cloned this today (and had the same error yesterday too). Google still finds the file in your repository.. but it seems gone when I look.

**Comment by uday610** [comment]
no longer applicable now as file has changed
