### ISSUE TITLE
2019. 2 compatibility and errors 

### ISSUE THREAD

**Issue by beldachi** [Xilinx/XRT#2754]
I downloaded the latest version of the XRT:
 
[XRT 2019.2] https://github.com/Xilinx/XRT/tree/2019.2

 I run the build.sh , I receive two errors 

runtime_src/core/pcie/emulation/common_em/CMakeFiles/common_em_objects.dir/build.make:166: recipe for target 'runtime_src/core/pcie/emulation/common_em/CMakeFiles/common_em_objects.dir/rpc_messages.pb.cc.o' failed
make[2]: *** [runtime_src/core/pcie/emulation/common_em/CMakeFiles/common_em_objects.dir/rpc_messages.pb.cc.o] Error 1
CMakeFiles/Makefile2:2334: recipe for target 'runtime_src/core/pcie/emulation/common_em/CMakeFiles/common_em_objects.dir/all' failed
make[1]: *** [runtime_src/core/pcie/emulation/common_em/CMakeFiles/common_em_objects.dir/all] Error 2

I have attached the related terminal messages.
Could you please advise me what is the issue might be?

Thanks for your time.

---------------------------------------------------------------------------------------------
[ 24%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionDebugData.cxx.o
runtime_src/core/pcie/emulation/common_em/CMakeFiles/common_em_objects.dir/build.make:166: recipe for target 'runtime_src/core/pcie/emulation/common_em/CMakeFiles/common_em_objects.dir/rpc_messages.pb.cc.o' failed
make[2]: *** [runtime_src/core/pcie/emulation/common_em/CMakeFiles/common_em_objects.dir/rpc_messages.pb.cc.o] Error 1
CMakeFiles/Makefile2:2334: recipe for target 'runtime_src/core/pcie/emulation/common_em/CMakeFiles/common_em_objects.dir/all' failed
make[1]: *** [runtime_src/core/pcie/emulation/common_em/CMakeFiles/common_em_objects.dir/all] Error 2
[ 25%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionSchedulerFW.cxx.o
[ 26%] Building CXX object xma/src/xmaapi/CMakeFiles/xma2api.dir/xma_utils.cpp.o
[ 26%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clGetProgramBuildInfo.cpp.o
[ 26%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clGetDeviceInfo.cpp.o
[ 27%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clCreatePipe.cpp.o
[ 27%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clGetEventInfo.cpp.o
[ 27%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionMemTopology.cxx.o
[ 27%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionConnectivity.cxx.o
[ 27%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionIPLayout.cxx.o
[ 27%] Linking CXX shared library libxma2api.so
[ 27%] Built target xma2api
[ 27%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionDebugIPLayout.cxx.o
[ 27%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clRetainContext.cpp.o
[ 27%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clCreateUserEvent.cpp.o
[ 27%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clSVMFree.cpp.o
[ 28%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clGetPlatformIDs.cpp.o
[ 29%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionDesignCheckPoint.cxx.o
[ 29%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionClockFrequencyTopology.cxx.o
[ 29%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionMCS.cxx.o
[ 29%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionBMC.cxx.o
[ 29%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionBuildMetadata.cxx.o
[ 29%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueNativeKernel.cpp.o
[ 29%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clAcquirePipeBuffer.cpp.o
[ 30%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionKeyValueMetadata.cxx.o
[ 30%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueFillImage.cpp.o
[ 30%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clCreateSampler.cpp.o
[ 31%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/enqueue.cpp.o
[ 31%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionUserMetadata.cxx.o
[ 31%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clReleaseProgram.cpp.o
[ 31%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueReadImage.cpp.o
[ 31%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueMigrateMemObjects.cpp.o
[ 31%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionPDI.cxx.o
[ 31%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionBitstreamPartialPDI.cxx.o
[ 31%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionPartitionMetadata.cxx.o
[ 32%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueWriteBuffer.cpp.o
[ 33%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionEmulationData.cxx.o
[ 33%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clGetKernelInfo.cpp.o
[ 33%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clCreateCommandQueue.cpp.o
[ 33%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionSystemMetadata.cxx.o
[ 33%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionSoftKernel.cxx.o
[ 33%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/SectionFlash.cxx.o
[ 33%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/DTC.cxx.o
[ 33%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clReadPipeBuffers.cpp.o
[ 33%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clRetainCommandQueue.cpp.o
[ 34%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clReleaseSampler.cpp.o
[ 34%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueSVMUnmap.cpp.o
[ 35%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/DTCStringsBlock.cxx.o
[ 35%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueCopyImageToBuffer.cpp.o
[ 35%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/FDTNode.cxx.o
[ 35%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clSetMemObjectDestructorCallback.cpp.o
[ 35%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clCreateImage2D.cpp.o
[ 35%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/FDTProperty.cxx.o
[ 36%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clRetainProgram.cpp.o
[ 36%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clGetCommandQueueInfo.cpp.o
[ 36%] Building CXX object runtime_src/tools/xclbin/CMakeFiles/xclbinutil.dir/XclBinSignature.cxx.o
[ 36%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueCopyBufferToImage.cpp.o
[ 36%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clGetImageInfo.cpp.o
[ 36%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clCreateBuffer.cpp.o
[ 37%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueNDRangeKernel.cpp.o
[ 37%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueCopyBuffer.cpp.o
[ 37%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clCreateImage3D.cpp.o
[ 37%] Linking CXX executable xclbinutil
[ 37%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clCreateKernel.cpp.o
[ 37%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clGetProgramInfo.cpp.o
[ 38%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clSVMAlloc.cpp.o
[ 38%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueWriteImage.cpp.o
[ 38%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueUnmapMemObject.cpp.o
[ 38%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clRetainKernel.cpp.o
[ 39%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clCreateContextFromType.cpp.o
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x11): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
[ 39%] Built target xclbinutil
[ 39%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clCreateContext.cpp.o
[ 39%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clGetKernelWorkGroupInfo.cpp.o
[ 39%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clCreateSubDevices.cpp.o
[ 39%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clSetUserEventStatus.cpp.o
[ 40%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueBarrier.cpp.o
[ 40%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueTask.cpp.o
[ 40%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clReleaseContext.cpp.o
[ 40%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clCreateProgramWithBinary.cpp.o
[ 40%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clCreateKernelsInProgram.cpp.o
[ 41%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueMapBuffer.cpp.o
[ 41%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clReleaseKernel.cpp.o
[ 41%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clReleaseEvent.cpp.o
[ 41%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clRetainEvent.cpp.o
[ 41%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clCreateHostPipe.cpp.o
[ 42%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clLinkProgram.cpp.o
[ 42%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clCreateProgramWithSource.cpp.o
[ 42%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clGetPipeInfo.cpp.o
[ 42%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clSetPrintfCallback.cpp.o
[ 42%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clSetCommandQueueProperty.cpp.o
[ 43%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueWriteBufferRect.cpp.o
[ 43%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clGetDeviceIDs.cpp.o
[ 43%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clRetainSampler.cpp.o
[ 43%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueMarkerWithWaitList.cpp.o
[ 44%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clReleasePipeBuffer.cpp.o
[ 44%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clCreateSubBuffer.cpp.o
[ 44%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueMapImage.cpp.o
[ 44%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clUnloadCompiler.cpp.o
[ 44%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clFlush.cpp.o
[ 45%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueReadBufferRect.cpp.o
[ 45%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clGetKernelArgInfo.cpp.o
[ 45%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clGetExtensionFunctionAddress.cpp.o
[ 45%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clReleaseCommandQueue.cpp.o
[ 45%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueWaitForEvents.cpp.o
[ 46%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clCreateImage.cpp.o
[ 46%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clGetEventProfilingInfo.cpp.o
[ 46%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clGetSamplerInfo.cpp.o
[ 46%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueFillBuffer.cpp.o
[ 46%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clWaitForEvents.cpp.o
[ 47%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clSetKernelArg.cpp.o
[ 47%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clBuildProgram.cpp.o
[ 47%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clGetMemObjectInfo.cpp.o
[ 47%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clGetPlatformInfo.cpp.o
[ 47%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clEnqueueCopyBufferRect.cpp.o
[ 48%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clSetKernelArgSVMPointer.cpp.o
[ 48%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clCreateProgramWithBuiltInKernels.cpp.o
[ 48%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clReleaseMemObject.cpp.o
[ 48%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/clGetExtensionFunctionAddressForPlatform.cpp.o
[ 48%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/detail/program.cpp.o
[ 49%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/detail/device.cpp.o
[ 49%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/detail/context.cpp.o
[ 49%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/detail/sampler.cpp.o
[ 49%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/detail/memory.cpp.o
[ 50%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/detail/pipe.cpp.o
[ 50%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/detail/event.cpp.o
[ 50%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/detail/command_queue.cpp.o
[ 50%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/detail/kernel.cpp.o
[ 50%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/detail/platform.cpp.o
[ 51%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/icd/ocl_icd_bindings.cpp.o
[ 51%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/khronos/check_copy_overlap.cpp.o
[ 51%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/xlnx/clWriteStream.cpp.o
[ 51%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/xlnx/clCreateStream.cpp.o
[ 51%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/xlnx/xclGetComputeUnitInfo.cpp.o
[ 52%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/xlnx/clCreateStreamBuffer.cpp.o
[ 52%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/xlnx/xclGetMemObjectFd.cpp.o
[ 52%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/xlnx/clReleaseStreamBuffer.cpp.o
[ 52%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/xlnx/clReleaseStream.cpp.o
[ 52%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/xlnx/clPollStreams.cpp.o
[ 53%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/xlnx/xclGetMemObjectFromFd.cpp.o
[ 53%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/xlnx/clReadStream.cpp.o
[ 53%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/xlnx/xclGetXrtDevice.cpp.o
[ 53%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/xlnx/clGetMemObjDeviceAddress.cpp.o
[ 53%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/printf/rt_printf.cpp.o
[ 54%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/printf/rt_printf_impl.cpp.o
[ 54%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/plugin/xdp/profile.cpp.o
[ 54%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/plugin/xdp/debug.cpp.o
[ 54%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/api/plugin/xdp/appdebug.cpp.o
[ 55%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/core/program.cpp.o
[ 55%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/core/execution_context.cpp.o
[ 55%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/core/device.cpp.o
[ 55%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/core/context.cpp.o
[ 55%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/core/sampler.cpp.o
[ 56%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/core/compute_unit.cpp.o
[ 56%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/core/memory.cpp.o
[ 56%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/core/stream.cpp.o
[ 56%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/core/debug.cpp.o
[ 56%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/core/pipe.cpp.o
[ 57%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/core/event.cpp.o
[ 57%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/core/command_queue.cpp.o
[ 57%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/core/kernel.cpp.o
[ 57%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/core/platform.cpp.o
[ 57%] Building CXX object runtime_src/xocl/CMakeFiles/xocl.dir/xclbin/xclbin.cpp.o
[ 57%] Built target xocl
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
root@hpn-test002:build$
------------------------------------------------------------------------------------------------

**Comment by uday610** [comment]
this should be working,
