### ISSUE TITLE
Correct messages for device creation/probe in AWS

### ISSUE THREAD

**Issue by rradjabi** [Xilinx/XRT#29]
The following message is incorrect in some ways and it is overly alarming in some ways. Make it more appropriate and tone it down.
```
1. [0]user:0x1042:0x7:[???:??:0]
2. xclProbe found 1 FPGA slots with xocl driver running
3. WARNING: AwsXcl - Cannot open userPF: /dev/dri/renderD0
4. WARNING: AwsXcl isGood: invalid user handle.
5. WARNING: xclOpen Handle check failed
6. [0]user:0xf000:0x1d51:[xocl:2017.4.5:128]
7. device[0].user_instance : 128
8. AFI not yet loaded, proceed to download.
```
L2) "1 FPGA slots" -> "1 FPGA slot(s)"
L2) "with xocl driver running" is probably not correct to say.
L3-5) can we suppress these messages?
Add a message that indicates a shell is not found, initializing or loading a default shell for SDAccel.

**Comment by stsoe** [comment]
Obsolete
