### ISSUE TITLE
code cleanup needed for clock_freq_topology related code

### ISSUE THREAD

**Issue by maxzhen** [Xilinx/XRT#30]
Had some discussion with Hem about freq topology code and I'm listing some cleanup work here:
1. ocl_get_clock_freq_topology icap interface should be removed and the related functionality should be moved into ocl_set_freq icap interface. We don't need to expose freq toplology outside of icap.
2. Correct locking is needed in icap_ocl_get_freqscaling() and icap_ocl_get_clock_freq_topology(). They are currently commented out.
3. Correct locking is needed in clock_freq_topology_show() since sysfs interface is also an entry point into icap subdevice.

**Comment by stsoe** [comment]
Fixed
