### ISSUE TITLE
XRT install failed on centos 7.3

### ISSUE THREAD

**Issue by yingsto** [Xilinx/XRT#3173]
The details as follows:
sudo yum install xrt_201920.2.3.0_7.3.1611-xrt.rpm
"
Loaded plugins: auto-update-debuginfo, fastestmirror, langpacks
Checking xrt_201920.2.3.0_7.3.1611-xrt.rpm: xrt-2.3.0-1.x86_64
xrt_201920.2.3.0_7.3.1611-xrt.rpm will be installed
Resolving dependencies
-> Checking transaction
---> Package xrt.x86_64.0.2.3.0-1 will be installed
-> Processing dependencies libstdc ++. So.6 (CXXABI_1.3.9) (64bit), which is required by the package xrt-2.3.0-1.x86_64
Loading mirror speeds from cached hostfile
 * base: mirrors.163.com
 * centos-sclo-rh: mirrors.cn99.com
 * centos-sclo-sclo: mirrors.cn99.com
 * epel: mirrors.aliyun.com
 * epel-debuginfo: mirrors.aliyun.com
 * extras: mirrors.cn99.com
 * updates: mirrors.cn99.com
-> Processing dependencies libstdc ++. So.6 (GLIBCXX_3.4.20) (64bit), which is required by the package xrt-2.3.0-1.x86_64
-> Processing dependencies libstdc ++. So.6 (GLIBCXX_3.4.21) (64bit), which is required by the package xrt-2.3.0-1.x86_64
-> Processing the dependency libstdc ++. So.6 (GLIBCXX_3.4.22) (64bit), which is required by the package xrt-2.3.0-1.x86_64
-> Resolve dependencies
Error: Package: xrt-2.3.0-1.x86_64 (/xrt_201920.2.3.0_7.3.1611-xrt)
          Required: libstdc ++. So.6 (GLIBCXX_3.4.20) (64bit)
Error: Package: xrt-2.3.0-1.x86_64 (/xrt_201920.2.3.0_7.3.1611-xrt)
          Required: libstdc ++. So.6 (GLIBCXX_3.4.22) (64bit)
Error: Package: xrt-2.3.0-1.x86_64 (/xrt_201920.2.3.0_7.3.1611-xrt)
          Required: libstdc ++. So.6 (GLIBCXX_3.4.21) (64bit)
Error: Package: xrt-2.3.0-1.x86_64 (/xrt_201920.2.3.0_7.3.1611-xrt)
          Required: libstdc ++. So.6 (CXXABI_1.3.9) (64bit)
 You can try to add --skip-broken option to solve the problem
** Found 5 existing RPM database problems, the output of 'yum check' is as follows:
containerd.io-1.2.10-3.2.el7.x86_64 has installed conflicts containerd: containerd.io-1.2.10-3.2.el7.x86_64
containerd.io-1.2.10-3.2.el7.x86_64 has installed conflict runc: containerd.io-1.2.10-3.2.el7.x86_64
ipa-client-4.4.0-12.el7.centos.x86_64 has installed conflict freeipa-client: ipa-client-4.4.0-12.el7.centos.x86_64
ipa-client-common-4.4.0-12.el7.centos.noarch has installed conflicts freeipa-client-common: ipa-client-common-4.4.0-12.el7.centos.noarch
ipa-common-4.4.0-12.el7.centos.noarch has installed conflict freeipa-common: ipa-common-4.4.0-12.el7.centos.noarch
"

**Comment by stsoe** [comment]
CentOS7.3 is not supported.
