### ISSUE TITLE
axlf length mismatch

### ISSUE THREAD

**Issue by martin31821** [Xilinx/XRT#3216]
I compiled an OpenCL kernel using v++ into an .xclbin file against the xilinx_u280_xdma_201920_3 platform.

When I try to load it using `clCreateProgramWithBinary`, I'm getting the error `axlf length mismatch` and return code `-42`. 

I digged within the source code and it seems to be that either my header is wrong or the file is not written completely to disk. 
How can I debug this problem further?

**Comment by uday610** [comment]
Please reach out to Vitis support as seems like v++ compilation issue
