### ISSUE TITLE
Build issue for vcu1525 on RHEL 7.6

### ISSUE THREAD

**Issue by bo-quan** [Xilinx/XRT#3381]
We're trying to build the 2019.1 branch code with vcu1525 installed on RHEL 7.6 by following instructions in https://xilinx.github.io/XRT/2019.1/html/build.html, but the build.sh script ran into a Boost library issue:

"
-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:948 ] Boost_USE_MULTITHREADED = TRUE

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:950 ] Boost_USE_STATIC_LIBS = ON

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:952 ] Boost_USE_STATIC_RUNTIME = 

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:954 ] Boost_ADDITIONAL_VERSIONS = 

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:956 ] Boost_NO_SYSTEM_PATHS = 

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1024 ] Declared as CMake or Environmental Variables:

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1026 ]   BOOST_ROOT = 

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1028 ]   BOOST_INCLUDEDIR = 

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1030 ]   BOOST_LIBRARYDIR = /usr/lib64/

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1032 ] _boost_TEST_VERSIONS = 1.61.0;1.61;1.60.0;1.60;1.59.0;1.59;1.58.0;1.58;1.57.0;1.57;1.56.0;1.56;1.55.0;1.55;1.54.0;1.54;1.53.0;1.53;1.52.0;1.52;1.51.0;1.51;1.50.0;1.50;1.49.0;1.49;1.48.0;1.48;1.47.0;1.47;1.46.1;1.46.0;1.46;1.45.0;1.45;1.44.0;1.44;1.43.0;1.43;1.42.0;1.42;1.41.0;1.41;1.40.0;1.40;1.39.0;1.39;1.38.0;1.38;1.37.0;1.37;1.36.1;1.36.0;1.36;1.35.1;1.35.0;1.35;1.34.1;1.34.0;1.34;1.33.1;1.33.0;1.33

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1125 ] location of version.hpp: /usr/include/boost/version.hpp

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1149 ] version.hpp reveals boost 1.53.0

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1235 ] guessed _boost_COMPILER = -gcc63

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1245 ] _boost_MULTITHREADED = -mt

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1288 ] _boost_RELEASE_ABI_TAG = -

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1290 ] _boost_DEBUG_ABI_TAG = -d

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1344 ] _boost_LIBRARY_SEARCH_DIRS_RELEASE = /usr/lib64;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH_boost_LIBRARY_SEARCH_DIRS_DEBUG   = /usr/lib64;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1483 ] Searching for SYSTEM_LIBRARY_RELEASE: boost_system-gcc63-mt-1_53;boost_system-gcc63-mt;boost_system-mt-1_53;boost_system-mt;boost_system

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:378 ]  Boost_LIBRARY_DIR_RELEASE = /usr/lib64 _boost_LIBRARY_SEARCH_DIRS_RELEASE = /usr/lib64;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1525 ] Searching for SYSTEM_LIBRARY_DEBUG: boost_system-gcc63-mt-d-1_53;boost_system-gcc63-mt-d;boost_system-mt-d-1_53;boost_system-mt-d;boost_system-mt;boost_system

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:378 ]  Boost_LIBRARY_DIR_DEBUG = /usr/lib64 _boost_LIBRARY_SEARCH_DIRS_DEBUG = /usr/lib64;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1483 ] Searching for FILESYSTEM_LIBRARY_RELEASE: boost_filesystem-gcc63-mt-1_53;boost_filesystem-gcc63-mt;boost_filesystem-mt-1_53;boost_filesystem-mt;boost_filesystem

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:378 ]  Boost_LIBRARY_DIR_RELEASE = /usr/lib64 _boost_LIBRARY_SEARCH_DIRS_RELEASE = /usr/lib64;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1525 ] Searching for FILESYSTEM_LIBRARY_DEBUG: boost_filesystem-gcc63-mt-d-1_53;boost_filesystem-gcc63-mt-d;boost_filesystem-mt-d-1_53;boost_filesystem-mt-d;boost_filesystem-mt;boost_filesystem

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:378 ]  Boost_LIBRARY_DIR_DEBUG = /usr/lib64 _boost_LIBRARY_SEARCH_DIRS_DEBUG = /usr/lib64;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1483 ] Searching for PROGRAM_OPTIONS_LIBRARY_RELEASE: boost_program_options-gcc63-mt-1_53;boost_program_options-gcc63-mt;boost_program_options-mt-1_53;boost_program_options-mt;boost_program_options

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:378 ]  Boost_LIBRARY_DIR_RELEASE = /usr/lib64 _boost_LIBRARY_SEARCH_DIRS_RELEASE = /usr/lib64;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1525 ] Searching for PROGRAM_OPTIONS_LIBRARY_DEBUG: boost_program_options-gcc63-mt-d-1_53;boost_program_options-gcc63-mt-d;boost_program_options-mt-d-1_53;boost_program_options-mt-d;boost_program_options-mt;boost_program_options

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:378 ]  Boost_LIBRARY_DIR_DEBUG = /usr/lib64 _boost_LIBRARY_SEARCH_DIRS_DEBUG = /usr/lib64;NO_DEFAULT_PATH;NO_CMAKE_FIND_ROOT_PATH

-- [ /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1595 ] Boost_FOUND = 1

CMake Error at /usr/local/share/cmake-3.6/Modules/FindBoost.cmake:1753 (message):

  Unable to find the requested Boost libraries.

  Boost version: 1.53.0

  Boost include path: /usr/include

  Could not find the following static Boost libraries:

          boost_program_options

  Some (but not all) of the required Boost libraries were found.  You may

  need to install these additional Boost libraries.  Alternatively, set

  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT

  to the location of Boost.

Call Stack (most recent call first):

  runtime_src/tools/xclbin/CMakeLists.txt:5 (find_package) 
"

**Comment by stsoe** [comment]
This must be obsolete by now.   We build XRT in our CI on CentOS7.6 and I believe folks are building locally on RHEL7.6 also.  You probably have to debug this and figure out why it is failing.  We don't have the resources to track this type of error down given that we build and release on CentOS7.6.
