### ISSUE TITLE
xclRegRead(), xclRegWrite() APIs undocumented

### ISSUE THREAD

**Issue by gareth-xlnx** [Xilinx/XRT#3431]
In the [current API documentation](https://xilinx.github.io/XRT/2019.2/html/index.html), the `xclRead()/xclWrite()` APIs [are shown as deprecated](https://xilinx.github.io/XRT/2019.2/html/xrt.main.html?highlight=xclread#c.xclRead) in favour of `xclRegRead()/xclRegWrite()` but these new APIs do not appear to documented.

**Comment by maxzhen** [comment]
They are not official APIs yet. The document is in https://github.com/Xilinx/XRT/blob/master/src/runtime_src/core/include/experimental/xrt-next.h
