### ISSUE TITLE
Question: how does XRT manage OpenCL platform and device information

### ISSUE THREAD

**Issue by boxerab** [Xilinx/XRT#3628]
After I install XRT, and I then make a programmatic OpenCL query about the available platforms, is this function call managed by XRT? i.e. is XRT acting as an OpenCL ICD loader ? And if it is, where is the code that manages these calls ?
Thanks!

**Comment by larry9523** [comment]
If your host application is linked to OpenCL.so, which is acting like an ICD loader, it will search for platforms under /etc/OpenCL/vendors. After installing XRT, you will have 
#cat /etc/OpenCL/vendors/xilinx.icd
libxilinxopencl.so
which will be loaded by ICD loader.

**Comment by boxerab** [comment]
Thanks, @larry9523 !
