### ISSUE TITLE
xclbin from software/hardware emu mode cannot be loaded by clBuildProgram

### ISSUE THREAD

**Issue by boxerab** [Xilinx/XRT#3669]
I am only able to load the kernel generated from hardware link, not from emulation.

**Comment by stsoe** [comment]
@boxerab Please use clCreateProgramWithBinary to load xclbin.   It is necessary to set XCL_EMULATION_MODE to either sw_emu or hw_emu if the xclbin was created for either.

**Comment by boxerab** [comment]
Thanks. Actually, my mistake, I did use `clCreateProgramWithBinary`. So, I need to set `XCL_EMULATION_MODE` when calling
`clCreateProgramWithBinary` ?

**Comment by stsoe** [comment]
Yes,  run your application with XCL_EMULATION_MODE set per how the xclbin was created.
FYI, we do have a change request for determining the flow based on the xclbin metadata, but today you have to set the env var.

**Comment by boxerab** [comment]
Great, thanks. Yes, it would be handy to deduce emulation from the binary.
