### ISSUE TITLE
Question: clEnqueueNDRangeKernel and cl_event* parameter

### ISSUE THREAD

**Issue by boxerab** [Xilinx/XRT#3685]
The last parameter of `clEnqueueNDRangeKernel` allows a user to get a `cl_event` linked to the kernel.
https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clEnqueueNDRangeKernel.html
If I wait for this event to complete, does completion indicate that the kernel has been successfully enqueued, or that
it has been successfully executed? From timing I am seeing, it looks like it indicates execution.
Thanks.

**Comment by stsoe** [comment]
@boxerab The event indicates the kernel has finished executing.   Enqueue is complete when clEnqueueNDRangeKernel returns.

**Comment by boxerab** [comment]
Thank you!
