### ISSUE TITLE
XMA testing script fail to pass on a clean install

### ISSUE THREAD

**Issue by gbonneau-hardent** [Xilinx/XRT#3791]
Trying to build the xma test executable on a clean install will fail. Reproduce step:
1- Build the XRT
2- Install the XRT
3- Go to the XRT/tests/xma directory
4- Run the xma_tests.sh script
5- The testing will fail. 

Note: I didn't investigate the details of the failing.

**Comment by sarab96** [comment]
Please ignore those XMA unit tests. those are obsolete. New XMA test will be added in future.
