### ISSUE TITLE
Installation fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by xuluna** [Xilinx/XRT#3813]
modprobe: ERROR: could not insert 'xclmgmt': Unknown symbol in module, or unknown parameter (see dmesg)

$ uname -r
4.15.0-112-generic

$dmesg
[  627.528855] xclmgmt: Unknown symbol fpga_mgr_unregister (err 0)
[  627.529014] xclmgmt: Unknown symbol fpga_mgr_register (err 0)

**Comment by maxzhen** [comment]
you probably did not have linux-modules-extra-`uname -r` installed?

**Comment by xuluna** [comment]
> you probably did not have linux-modules-extra-`uname -r` installed?

Yes, thank you!
