### ISSUE TITLE
Update xma-samples repository with a working solution to be in sync with current XRT release

### ISSUE THREAD

**Issue by gbonneau-hardent** [Xilinx/XRT#3823]
It's painful to learn XMA. I've tried very hard to learn the API using a very simple example. The one which seems to be the more relevant was the copy encoder included with the xma-samples repository. Note that I don't want to use for now an accelerator PCIe board. Before committing to buying the hardware I want to learn at least the basic of the processing capabilities through either software or hardware emulation.

I have found the hard way that XMA doesn't work with software emulation. And this is not documented. Then I tried with hardware emulation which is supported but It failed the compilation of the copy encoder standalone application with some issues. I can only conclude that hardware emulation has never been QA. Then I checked the XMA testing unit application to give me some hints and discovered that they didn't compile and are not up to date. Thus XMA is released without minimal unit testing to check that nothing is broken. I am going to switch in rant mode at this point and say that this is poor engineering and development flow.

Using only the documentation to learn how to use the XMA API  without a simple application that would work with the current XRT released is painful.

Please provide an XMA sample(s) that is working against the current XRT release with both hardware and hardware emulation.

**Comment by sarab96** [comment]
Please use Xilixn github examples and U30 software stack examples
