### ISSUE TITLE
Check FPGA status after xbutil reset -h

### ISSUE THREAD

**Issue by chienwei-lan** [Xilinx/XRT#383]
now, xbutil reset -h is performing a PCIe secondary bus(root complex) reset, return xbutil reset successfully if it's performed successfully .  

We should check FPGA status after performing xbutil reset -h, decide it's a successful reset or not.

Or user will be confused if reset is successful but FPGA is still in bad status.

**Comment by uday610** [comment]
@chienwei-lan , is this done now?

**Comment by uday610** [comment]
obsolated today
