### ISSUE TITLE
Concurrent kernels not being generated

### ISSUE THREAD

**Issue by boxerab** [Xilinx/XRT#3894]
Following the documentation [here](https://www.xilinx.com/html_docs/xilinx2020_1/vitis_doc/buildingdevicebinary.html#yzb1524519238289), I have add a cfg file with line

`nk=FOO:3`

which I reference when I run the vitis linker.

But, when I call `clCreateKernel` with kernel name `FOO_1`  :
 
`auto kernel = clCreateKernel(program, "FOO_1", &error);`

I get the following XRT error:

`[XRT] ERROR: kernel 'FOO_1' not found`

Passing in `FOO` does work.

What am I missing ?
Thanks!

**Comment by boxerab** [comment]
It looks like:

`FOO:{FOO_1}` will work. The documents should probably be updated to reflect this.

**Comment by uday610** [comment]
@boxerab , that syntax is documented in host coding section (your link is pointing to the kernel compilation section).

https://www.xilinx.com/html_docs/xilinx2020_1/vitis_doc/devhostapp.html#kol1557424570275__section_kxw_rvc_ljb
