### ISSUE TITLE
Support for 5.4+ kernel ?

### ISSUE THREAD

**Issue by boxerab** [Xilinx/XRT#4002]
When may we expect support for newer kernels, and Ubuntu 20.04, for example ?

**Comment by boxerab** [comment]
As a matter of fact, it looks like at least the U250 is supported now on Ubuntu 20, using Ubuntu 18 deb packages.

**Comment by keryell** [comment]
At least we are using XRT compiled from master branch with Ubuntu 20.04 and 5.4 kernel.

**Comment by boxerab** [comment]
Yes, I am able to run the U250 with the 5.4.0-42 kernel.
