### ISSUE TITLE
Broken links in the .rst documentation

### ISSUE THREAD

**Issue by keryell** [Xilinx/XRT#4036]
For example on https://github.com/Xilinx/XRT/blob/master/src/runtime_src/doc/toc/system_requirements.rst the links are broken.

**Comment by uday610** [comment]
when linking one .rst file from another .rst file, I have seen the link does not work. After creating the HTML files those work. You can check the HTML files https://xilinx.github.io/XRT/index.html there link should be working

**Comment by keryell** [comment]
Could you make them to work for both, like in https://github.com/triSYCL/triSYCL/blob/master/doc/testing.rst ?

**Comment by keryell** [comment]
This is probably a limitation of the GitHub ReST renderer with the `:ref:` syntax

**Comment by uday610** [comment]
I unable to fix this, hence closing. When we have a techdoc expert we can address this issue.
