### ISSUE TITLE
Buffer created with flag CL_MEM_READ_ONLY | CL_MEM_HOST_WRITE_ONLY is still copying buffer data from card to host when mapped with clEnqueueMapBuffer

### ISSUE THREAD

**Issue by boxerab** [Xilinx/XRT#4046]
I have created a buffer marked `CL_MEM_READ_ONLY | CL_MEM_HOST_WRITE_ONLY`, meaning that the kernel can only read from the buffer and the host can only write to the buffer.

Therefore, there is no need to copy the data back to the host when I call `clEnqueueMapBuffer` with
`CL_MAP_WRITE` .

Using `xbutil top`, I see that the data is in fact copied.

**Comment by uday610** [comment]
@boxerab , Can you try clEnqueueMapBuffer with CL_MAP_WRITE_INVALIDATE_REGION ?

**Comment by boxerab** [comment]
@uday610 yes! that fixed the issue. Thank you.
