### ISSUE TITLE
clReleaseStream() does not clear the argument mapping

### ISSUE THREAD

**Issue by haeseunglee** [Xilinx/XRT#425]
clReleaseStream() should clear the argument mapping when it's called, but it's not happening.
So, when you create the same mapping again after call clReleaseStream(), you will get the error message like this: "Create Write Queue failed ret=-30"

**Comment by stsoe** [comment]
Discussed with Max. We will fix kernel argument reference counting of memory objects.

**Comment by uday610** [comment]
QDMA is no longer supported
