### ISSUE TITLE
Build failure on Ubuntu 18.04

### ISSUE THREAD

**Issue by rashmi2383** [Xilinx/XRT#4260]
I am seeing the following error while running the build script. 

[ 89%] Building CXX object runtime_src/core/pcie/tools/xbmgmt/CMakeFiles/xbmgmt.dir/firmware_image.cpp.o
In file included from /usr/local/boost_1_67_0/boost/process/detail/execute_impl.hpp:24:0,
                 from /usr/local/boost_1_67_0/boost/process/child.hpp:22,
                 from /usr/local/boost_1_67_0/boost/process/async_system.hpp:22,
                 from /usr/local/boost_1_67_0/boost/process.hpp:24,
                 from /home/rashmi/XRT/src/runtime_src/core/tools/common/Process.cpp:45:
/usr/local/boost_1_67_0/boost/process/detail/posix/executor.hpp: In member function ‘void boost::process::detail::posix::executor<Sequence>::write_error(const std::error_code&, const char*) [with Sequence = boost::fusion::joint_view<boost::fusion::tuple<boost::process::detail::posix::exe_cmd_init<char>, boost::process::detail::posix::env_init<char> >, boost::fusion::filter_view<const boost::fusion::tuple<boost::filesystem::path&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, boost::process::detail::posix::pipe_out<1, -1>&, boost::process::detail::posix::pipe_out<2, -1>&, boost::process::basic_environment<char>&>, boost::process::detail::is_initializer<mpl_::arg<-1> > > > ’:
/usr/local/boost_1_67_0/boost/process/detail/posix/executor.hpp:191:16: error: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Werror=unused-result]
         ::write(_pipe_sink, &len, sizeof(int));
         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/boost_1_67_0/boost/process/detail/posix/executor.hpp:194:16: error: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Werror=unused-result]
         ::write(_pipe_sink, &len, sizeof(int));
         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/boost_1_67_0/boost/process/detail/posix/executor.hpp:195:16: error: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Werror=unused-result]
         ::write(_pipe_sink, msg, len);
         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
[ 89%] Building CXX object runtime_src/xdp/CMakeFiles/xdp_hal_plugin.dir/profile/writer/hal/hal_summary_writer.cpp.o
[ 89%] Building CXX object runtime_src/core/tools/xbutil2/CMakeFiles/xbutil2.dir/__/common/ProgressBar.cpp.o
cc1plus: all warnings being treated as errors
runtime_src/core/tools/xbutil2/CMakeFiles/xbutil2.dir/build.make:94: recipe for target 'runtime_src/core/tools/xbutil2/CMakeFiles/xbutil2.dir/__/common/Process.cpp.o' failed
make[2]: *** [runtime_src/core/tools/xbutil2/CMakeFiles/xbutil2.dir/__/common/Process.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 89%] Building CXX object runtime_src/core/pcie/tools/xbmgmt/CMakeFiles/xbmgmt.dir/xbmgmt.cpp.o
[ 90%] Linking CXX shared module libxdp_hal_plugin.so
[ 90%] Built target xdp_hal_plugin
[ 90%] Building CXX object runtime_src/core/pcie/tools/xbmgmt/CMakeFiles/xbmgmt.dir/xspi.cpp.o
[ 91%] Building CXX object runtime_src/xdp/CMakeFiles/oclxdp.dir/profile/plugin/ocl/xocl_profile.cpp.o
[ 91%] Building CXX object runtime_src/xdp/CMakeFiles/oclxdp.dir/profile/plugin/ocl/xocl_profile_cb.cpp.o
CMakeFiles/Makefile2:2625: recipe for target 'runtime_src/core/tools/xbutil2/CMakeFiles/xbutil2.dir/all' failed
make[1]: *** [runtime_src/core/tools/xbutil2/CMakeFiles/xbutil2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 92%] Linking CXX executable xbmgmt
[ 94%] Built target xbmgmt
[ 94%] Linking CXX shared library liboclxdp.so
[ 94%] Built target oclxdp
[ 94%] Linking CXX executable xbutil
[ 94%] Built target xbutil
Makefile:181: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by stsoe** [comment]
Hello.  Thank you for your report.  boost_1_67_0 appears to be some locally installed version Boost.  The system version we use to build XRT on Ubuntu18.04 is 1.65.1. We support building of XRT in stock version Ubuntu 16.04, 18.04, and 20.04 with the assumption that the dependent libraries are installed with default apt get or by sourcing xrtdeps.sh per https://xilinx.github.io/XRT/master/html/build.html
