### ISSUE TITLE
Question: support for OpenCL popcount ?

### ISSUE THREAD

**Issue by boxerab** [Xilinx/XRT#4268]
This is a 1.2 feature

https://manpages.debian.org/unstable/opencl-1.2-man-doc/popcount.3clc.en.html

Is it present in XRT ? If not, is there a library I can use to perform efficient popcount on Alveo boards ?

Thanks!

**Comment by uday610** [comment]
Are you talking about OpenCl kernel code? Can you please confirm. 
Please show the usage with some sample code.

**Comment by boxerab** [comment]
Thanks, yes, this is for kernel code.

**Comment by uday610** [comment]
@boxerab , you can ask this in general Vitis support forum as XRT does not involve with the kernel support.  But in general, if you see Vitis examples, C Kernels are much more used and preferred for kernel coding. With C kernel you can get all functionalities and there are also several libraries.

**Comment by boxerab** [comment]
Thanks, @uday610 but I am a bit confused. By kernel code, I mean code I can put into an OpenCL kernel:

```
const char *KernelSource = "\n" \
"__kernel void pop_square(                                              \n" \
"   __global uint* input,        	                                    \n" \
"   __global uint* output,  		                                    \n" \
"   const unsigned uint count)                                          \n" \
"{                                                                      \n" \
"   int i = get_global_id(0);                                           \n" \
"   uint pop = popcount(input[i]);                                    	\n" \
"   if(i < count)                                                       \n" \
"       output[i] = input[i] * input[i];                                \n" \
"}                                                                      \n" \
"\n";
```

Isn't this handled by XRT ?

**Comment by boxerab** [comment]
I see now, I will ask about this on Vitis support forum.
