### ISSUE TITLE
Wrong xmaapi.h header copied to includes folder of XRT by the builder

### ISSUE THREAD

**Issue by gbonneau-hardent** [Xilinx/XRT#4497]
Once the build which was started with the script build.sh is finished, I have found that the Legacy XMA xmaapi.h header was copied to the includes folder of ../opt/xilinx/xrt/include/lib. This cause an issue for building an application that relies on this header since the XmaSingleton structure has changed with the new XMA 2 API. I am using branch 2020.1

**Comment by sarab96** [comment]
XMA legacy headers are in /opt/xilinx/xrt/include (to be removed in near future)
XMA2 headers are in /opt/xilinx/xrt/include/xma2

**Comment by gbonneau-hardent** [comment]
Indeed! Thanks for the head-up. However, this is somewhat confusing because the compile path of xmaapi.cpp for example uses the path "lib/xmaapi.h" with the correct version 2 include headers. Yet the build installs the include files of the legacy XMA within a folder with the same name lib. But this is probably for compatibility issues. Great then we can close this issue. - Thanks.
