### ISSUE TITLE
Double check timeouts for xbflash

### ISSUE THREAD

**Issue by cellery** [Xilinx/XRT#450]
People are seeing very long timeouts in xbflash. Should reduce this down to a few seconds.

**Comment by uday610** [comment]
@cellery , is this issue still valid?

**Comment by cellery** [comment]
Hi Uday, it is still valid. The two functions that need to be optimized are:

XSPI_Flasher::isFlashReady()
XSPI_Flasher::waitTxEmpty()

The code times out after what is supposed to be a couple seconds, but the delay calculation is not taking into account the time it takes to read flash registers, hence the timeout is much longer than its supposed to be. The fix should be calculating using the delay of flash read + the sleep time.

**Comment by uday610** [comment]
obsolated
