### ISSUE TITLE
XRT Master: 20 seconds to initialize OpenCL

### ISSUE THREAD

**Issue by boxerab** [Xilinx/XRT#4506]
Didn't have this with previous 2.7 release of XRT. When I use OpenCL to query the platform and device, it takes a very long time to return.

This is the call that takes 20 seconds:

 `cl_int status = clGetPlatformIDs(0, NULL, &numPlatforms);`

**Comment by stsoe** [comment]
Hi @boxerab This is not XRT spending 20 seconds, in fact the speed of clGetPlatformIDs itself was improved quite significantly in 2020.2 where it now avoids driver calls to open available devices.  Are you maybe using the ICD loader and impacted by other vendors libraries or just dynamic runtime loading on libraries in general?

**Comment by boxerab** [comment]
This issue is fixed in latest XRT version. Closing.
