### ISSUE TITLE
Please compile xdp with -Wall -Werror

### ISSUE THREAD

**Issue by stsoe** [Xilinx/XRT#461]
There are warnings out of xdp, please fix these and make sure the code compiles with -Wall and -Werror.
In src/runtime_src/CMakeLists.txt, move add_subdirectory(xdp) after -Wall -Werror.

**Comment by pgschuey** [comment]
Thanks for letting us know, Soren. I'm working on this now.

**Comment by stsoe** [comment]
Fixed in #473
