### ISSUE TITLE
Arm服务器上Xilinx XRT的编译问题

### ISSUE THREAD

**Issue by DaveAimee** [Xilinx/XRT#4696]
1. 编译报错

![图片1](https://user-images.githubusercontent.com/27729297/107008131-5f9d4b80-67ce-11eb-91f1-33e879a291e5.png)
2. 编译时是否需要安装Xilinx Vitis Software Platform
目前已经尝试下载了Xilinx_Unified_2020.2_1118_1232_Lin64.bin，但是在安装的时候提示：
![image](https://user-images.githubusercontent.com/27729297/107008201-780d6600-67ce-11eb-984a-1e00e4512ab3.png)

**Comment by maxzhen** [comment]
@DaveAimee please let us know the Linux kernel version (uname -r).

**Comment by DaveAimee** [comment]
My "uname -r" shows 4.14.0-115.el7a.0.1.aarch64, does xrt hava specific version requirements?

**Comment by DaveAimee** [comment]
Checked once again,found I forgot to run './build.sh clean' to clean some stale configs. My compile problem has been solved, Thanks!
