### ISSUE TITLE
DSA install should automatically unload and then reload drivers

### ISSUE THREAD

**Issue by sonals** [Xilinx/XRT#493]

**Comment by keryell** [comment]
Is it a real issue?
If I understand correctly for example the Alveo U200 documentation, flashing a DSA requires cold-booting the whole machine, so probably this unload/reload is just a side effect of the reboot...

**Comment by keryell** [comment]
That said, it would be nice if changing a DSA would not require rebooting the machine...

**Comment by uday610** [comment]
after shell package install, the reboot is required, this is a standard usage now.
