### ISSUE TITLE
DSA feature discovery based on VBNV name is hacky

### ISSUE THREAD

**Issue by maxzhen** [Xilinx/XRT#535]
https://github.com/Xilinx/XRT/blob/96f4059b0e6fcbf54dce5fedd73217078b73ae2c/src/runtime_src/driver/xclng/drm/xocl/subdev/feature_rom.c#L317
It's better to add the feature info to either:
DSA's feature ROM
OR
static table defined in devices.h and associate it with the correct device ID.

**Comment by stsoe** [comment]
Feature ROM would be ideal, but the info is not there.  I need to know, if a DSA (1) has ERT, (2) if ERT is there, does the CU address lookup through a table lookup, or is addressing consecutive, (3) does the DSA support CDMA.  

(3) will be addressed, I know, but I am not sure about (1) and (2).    I'd be happy to move the the information into the static tables in device.h if only I had a clue as how to determine which section correspond to which device and how I am supposed to add the information.

**Comment by maxzhen** [comment]
Lizhi knows better about the details. But basically, you just need to add member(s) to struct xocl_board_private, which will be populated by a XOCL_BOARD_xxx macro, which then will be associated with a particular (vendor, device, subdevice) triplet in XOCL_MGMT_PCI_IDS or XOCL_USER_XDMA_PCI_IDS. Take a look at struct xocl_board_private->board_name for example.

**Comment by stsoe** [comment]
I believe this has finally been taken care of.
