### ISSUE TITLE
The compiled documentation should not be in the source repository

### ISSUE THREAD

**Issue by keryell** [Xilinx/XRT#544]
There should be no https://github.com/Xilinx/XRT/tree/master/docs directory in the Git repository, since it is a by-product of the documentation compilation.

I hope that this is not directly used by https://xilinx.github.io/XRT/ ...

**Comment by keryell** [comment]
To make progress on this, one can look for example at https://github.com/triSYCL/triSYCL/blob/master/doc/architecture.rst#source-code-documentation about how to move the generated documentation into a separate branch.

**Comment by mamin506** [comment]
@keryell Hi, Ronan. The docs/ folder was removed from master branch. If you run build.sh, the document will be built in Release/runtime_src/doc/ folder. Only Sonal and Soren can publish documents to gh-pages branch. See #765.

**Comment by keryell** [comment]
That seems like a reasonable solution.
At least the git repository is quite cleaner now!
Thanks.
