### ISSUE TITLE
Integrate better test.rst documentation with build.rst

### ISSUE THREAD

**Issue by keryell** [Xilinx/XRT#548]
Now there is a good https://github.com/Xilinx/XRT/blob/master/src/runtime_src/doc/toc/build.rst talking about Release and Debug build, I have the feeling that most of the building part described in
https://github.com/Xilinx/XRT/blob/master/src/runtime_src/doc/toc/test.rst should be factorized out into `build.rst` and put into context.

**Comment by uday610** [comment]
@sonals , any plan/thought? Otherwise can we close this?

**Comment by uday610** [comment]
build and test documentation page is upgraded. no longer applicable
