### ISSUE TITLE
XRT_docs

### ISSUE THREAD

**Issue by durgabhavaniv** [Xilinx/XRT#5517]
I am not able to generate XRT_docs.

command used : 
./build.sh -docs -ertfw /opt/xilinx/xrt/share/fw/sched.bin
Facing issue:
make xrt_docs
make: *** No rule to make target 'xrt_docs'.  Stop.

**Comment by durgabhavaniv** [comment]
Hi able to fix this but facing issue as follows:
![Screenshot 2021-07-22 18:07:23](https://user-images.githubusercontent.com/42232855/126640330-4ea56ba0-9916-4ffd-a736-8fc97522967d.png)

**Comment by uday610** [comment]
@durgabhavaniv , document generation may not outside Xilinx. We don't support doc generation flow outside Xilinx. 

XRT team generates document and publish here: https://xilinx.github.io/XRT/master/html/index.html , so you can look into these HTML files if you require any information.

**Comment by uday610** [comment]
closed as per previous comment
