### ISSUE TITLE
Clean up the documentation in src/runtime_src/driver/include/xclhal2.h

### ISSUE THREAD

**Issue by keryell** [Xilinx/XRT#554]
There is a lot of errors when compiling the documentation from the comments extracted from this file.

**Comment by maxzhen** [comment]
The doc is built while building the whole XRT now. I do not see any errors. @keryell , please close this issue if it works for you. Or please let me know how to reproduce it.

**Comment by uday610** [comment]
all XRT APIs documentations are in github.io,
