### ISSUE TITLE
[XRT 2.11.0] Re-programming FPGA from different thread crashes the whole server

### ISSUE THREAD

**Issue by jstamel** [Xilinx/XRT#5546]
Running a simple OpenCL application that acquires a context for a device and then programs it from a different thread, causes the device as well as the whole server to crash. This happens only upon trying to reconfigure the device with a different xclbin file (not in case of 'skip reloading' xclbin).

The above scenario has been tested **On-Prem** as well as on **Amazon AWS** and **Microsoft Azure** clouds.

[Here](https://github.com/Xilinx/XRT/files/6900055/issue.zip) you can find all the code required for reproducing the issue.

- **Sample code**:

	``` cpp
	#include <iostream>
	#include <thread>
	#include "xcl2.hpp"

	void program_fn(cl::Device device, cl::Context context, std::string bit_file) {
		auto fileBuf = xcl::read_binary_file(bit_file);

		cl::Program::Binaries bins{{fileBuf.data(), fileBuf.size()}};

		cl::Program program = cl::Program(context, {device}, bins, nullptr, NULL);
	}

	int main(int argc, char **argv) {
		if (argc != 2) {
			std::cout << "usage: " << argv[0] << " <bitstream_file>" << std::endl;
			return 1;
		}

		auto device = xcl::get_xil_devices()[0];
		cl::Context context = cl::Context(device, nullptr, nullptr, nullptr, NULL);

	#ifdef ISSUE
		std::cout << "program device (different thread)" << std::endl;
		std::thread program_td(program_fn, device, context, std::string(argv[1]));
		program_td.join();
	#else
		std::cout << "program device (same thread)" << std::endl;
		program_fn(device, context, std::string(argv[1]));
	#endif

		return 0;
	}
	```

- **Steps to reproduce**:
	- Same thread (no issue)
	```bash
	source /opt/xilinx/xrt/setup.sh
	make ok
	./xrt-issue <bitstream_file>

	```
	- Different thread (issue)
	```bash
	source /opt/xilinx/xrt/setup.sh
	make issue
	./xrt-issue <bitstream_file>

	```

- Affected XRT versions
	- **202110.2.11.634** (2.11.0)

**Comment by stsoe** [comment]
@jstamel Thank you for a very good and simple test to reproduce.  I am seeing the same problem.
