### ISSUE TITLE
python_binding (Failed)

### ISSUE THREAD

**Issue by mashemat** [Xilinx/XRT#5611]
Hello,

I tried to install but I faced the following Error:
 5/11 Test  #5: python_binding ....................***Failed  

Traceback (most recent call last):
  File "/home/mashemat/XRT/src/../tests/python/200_binding/200_main.py", line 18, in <module>
    import pyxrt as pp
ImportError: /home/mashemat/XRT/build/Debug/opt/xilinx/xrt/python/pyxrt.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyThread_tss_get

Any Idea to fix?

Thanks,

**Comment by uday610** [comment]
Can you please let us know on what OS you are trying to build? Also what is Python version in your system?

**Comment by mashemat** [comment]
Hi uday610, 
Thanks for your reply! I am using ubuntu 18.04 & python 3.6. Would it be OK? Is there any package to install on ubuntu not from source?

Thanks,

**Comment by chvamshi-xilinx** [comment]
Hi @mashemat . That should be fine. Can you please check what is the output of
ldd /home/mashemat/XRT/build/Debug/opt/xilinx/xrt/python/pyxrt.cpython-36m-x86_64-linux-gnu.so

**Comment by sonals** [comment]
@mashemat, is this still an issue?

**Comment by mashemat** [comment]
Thanks for your email. Actually it was solved. The problem was the OFED
version that could not communicate with FPGA. I upgrade it and was solved.

**Comment by sonals** [comment]
Closing based on @mashemat feedback.
