### ISSUE TITLE
Dynamic loading in `xrt_xocl::hal::load_xdp()` assumes install directory is always `XILINX_XRT/lib`

### ISSUE THREAD

**Issue by evansmal** [Xilinx/XRT#5621]
# Summary
Trying to load OpenCL platforms or XRT devices will fail when the XRT libraries are not installed in `$XILINX_XRT/lib`. For example, if the binaries are installed in `/usr/lib64`, the following behavior is seen:

#### When using the OpenCL host API

```cpp
cl::Platform::get(&platforms);
std::cout << "Platforms: " << platforms.size() << std::endl; // this is always 0
```

This one is very confusing - since there are no errors and we instead get that there are no platforms. 

#### When using the XRT API

```cpp
unsigned int dev_index = 0;
auto device = xrt::device(dev_index); // this throws
```

This is less confusing, since an error is thrown.

# XRT Version

This issue still appears on `master`, but I was testing on the following build:

```
XRT build version: 2.8.0
Build hash: f19a872233fbfe2eb933f25fa3d9a780ced774e5
Build date: 2021-06-03 15:34:12
Git branch: 2020.2
```

# Possible Fixes

- Report the` dlopen` error ("library x not found")  when trying to get cl::Platform instead of reporting no platforms found. If someone is only using OpenCL, its confusing why no platforms are ever detected. We only figured this out after running the XRT API which throws [here](https://github.com/Xilinx/XRT/blob/7aba37d5ea0659ff7298a562447eba1f613965ad/src/runtime_src/xrt/device/hal.cpp#L280).

- Allow for users to supply a name for the [library directory other than `lib`](https://github.com/Xilinx/XRT/blob/7aba37d5ea0659ff7298a562447eba1f613965ad/src/runtime_src/xrt/device/hal.cpp#L276) through an environment variable, similar to what is done with `$XILINX_XRT`. This could be done using `lib` as default to make the change backwards compatible. 

If either of these fixes seem reasonable, I can submit a PR to address them.

**Comment by uday610** [comment]
If XRT is not installed then xilinx.icd file should be missing, and there is no way to load Xilinx library, ICD file is a must for OpenCL flow to pick the correct XIlinx runtime library. This is not the same with native XRT flow. So in that sense, this behavior is correct and there is no platform is reported.
Please let us know if you see something else. 
Thanks
Uday

**Comment by evansmal** [comment]
In my case the ICD file is present and points to the correct runtime library. This issue persists with the OpenCL flow when the ICD is installed correctly.

As I mentioned above, the issue is that the dlopen call that occurs in `xrt_xocl::hal::load_xdp()` assumes that the XRT shared objects are always located in `XILINX_XRT/lib`. This assumption is not documented and not all custom platforms will necessarily install runtime libraries in this directory. While this is not necessarily wrong, it would be nice if this was documented, or configurable in some way.

**Comment by stsoe** [comment]
@jvillarre @uday610 I think load_xdp is dead code so I am not really following @evansmal 's comment?  Any way, it is likely that other variants of the xdp DSO loading suffer the same problem.  Assigning to Jason so he can decide appropriate action, which I recommend should be a documentation fix.

**Comment by evansmal** [comment]
The exception thrown is the on the line I linked above. You can see it [here](https://github.com/Xilinx/XRT/blob/7aba37d5ea0659ff7298a562447eba1f613965ad/src/runtime_src/xrt/device/hal.cpp#L280). I couldn't find any other occurrences of `throw std::runtime_error("Library " + libname.string() + " not found!");` in the source code, so I assumed it came from there.
