### ISSUE TITLE
one API interface to perform AXI gate freeze and free from icap

### ISSUE THREAD

**Issue by maxzhen** [Xilinx/XRT#565]
Today, icap provide two separate APIs for AXI gate freeze and free. This is not good since these two steps should be done in one shot, always. We should, instead, just provide one API to perform AXI gate reset from icap. In this interface, we'll need to grab icap's mutex and perform AXI gate freeze and free.

**Comment by uday610** [comment]
@maxzhen , what is the status of this plan?

**Comment by maxzhen** [comment]
already done

**Comment by chandruFromTamil** [comment]
okay
