### ISSUE TITLE
aarch64 compatibility issue

### ISSUE THREAD

**Issue by luckyteddy** [Xilinx/XRT#568]
I tried to compile on an aarch64 server and found the error.
/home/xu/XRT/src/runtime_src/impl/cpu_em_math.cpp:65:4: error: #warning ForceFTZ needs an implentation [-Werror=cpp]
   #warning ForceFTZ needs an implentation
    ^~~~~~~
Further investigation found that the cpu_em_math.cpp file doesn't include (__aarch64__) action.

**Comment by mamin506** [comment]
This is a known issue for us. This file is obsoleted. We will remove it. @sonals
