### ISSUE TITLE
Makefiles in tests/xrt/ <> need to be validated (not working)

### ISSUE THREAD

**Issue by hcneema** [Xilinx/XRT#582]
1. Makefiles in individual tests are not working
2. They need to be adapted so that we pick up the utils.h from host_src area (so that every testcase doesnt need one copy).

**Comment by uday610** [comment]
@haeseung81 , can you please see if this issue is still valid?

**Comment by haeseung81** [comment]
I believe they are all fixed by now. All the makefiles and testcases are up-to-date.

**Comment by uday610** [comment]
closed
