### ISSUE TITLE
XRT fails build with: Imported target "Boost::filesystem" includes non-existent path "/include"

### ISSUE THREAD

**Issue by oscarkramer** [Xilinx/XRT#5940]
I cloned the XRT repo from github and followed the directions in a [link](https://xilinx.github.io/XRT/master/html/build.html) provided in the XRT/README.rst. When I run the XRT/build/build.sh script, I get:
```$ ./build.sh
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug ../../src
-- Host system processor is x86_64
-- Target system processor is x86_64
-- Looking for DRM - found at /usr 2.4.105
-- Looking for OPENCL - found at /usr 2.1 /usr/include
-- Looking for GIT - found at /bin/git
-- Enabling static artifacts of XRT
########### Looking for system BOOST ################
Boost_INCLUDE_DIRS=/usr/include
Boost_LIBRARY_DIRS=/usr/lib/x86_64-linux-gnu
-- XRT EA eula files  /opt/xilinx/XRT/src/../LICENSE
-- Platform/Linux (Ubuntu) (Kernel 5.11.0-37-generic)
-- Compiler: /bin/c++ /bin/cc
-- RapidJSON found. Headers: /usr/include
-- XRT xrt++ header files
-- xrt++.hpp
-- xrtexec.hpp
...
-- Configuring done
CMake Error in runtime_src/tools/xclbinutil/CMakeLists.txt:
  Imported target "Boost::system" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```
Same when I run using `sudo`. I added the print out of `Boost_INCLUDE_DIRS` and `Boost_LIBRARY_DIRS` in the CMakeLists.txt and that is indeed correct for my installation.

I also tried 

`./build.sh -with-static-boost /opt/xilinx/XRT/src/runtime_src/tools/scripts/boost/xrt`

after using the script to download and build an xrt-local boost package, but am seeing the same error.

Any ideas how to fix? I'm un Ubuntu 20.04 and presumably building XRT 2021.1. Thanks.

**Comment by stsoe** [comment]
Awesome.  Thanks for confirming.  I will close this issue then.
