### ISSUE TITLE
XRT disappeared from default location after "sudo" upgrading on Ubuntu

### ISSUE THREAD

**Issue by NadeemAtif-Alig** [Xilinx/XRT#5975]
I recently "sudo" upgraded my ubuntu OS (20.04 LTS) by using the "**sudo apt update && sudo apt upgrade**". After that, my xrt folder from the default location /opt/xilinx disappeared automatically. Can anyone please explain what is the matter? Thanks.

**Comment by keryell** [comment]
Perhaps related to a problem I mention in https://github.com/triSYCL/sycl/blob/sycl/unified/next/sycl/doc/GettingStartedXilinxFPGA.md#installing-the-xilinx-xrt-runtime

Search for `sudo apt-mark hold xrt` in the file.

**Comment by uday610** [comment]
Closing this as solution is provided by @keryell , please reopen if something else required.
