### ISSUE TITLE
`xbmgmt program` cannot create a shell partition

### ISSUE THREAD

**Issue by vkomenda** [Xilinx/XRT#6101]
I'm puzzled by this error message while trying to program the shell partition. Do you know what could be wrong there?

```
$ sudo /opt/xilinx/xrt/bin/xbmgmt program --shell /lib/firmware/xilinx/9964c19cdb53eb6c69b6fd2072401583/partition.xsabin -d 0000:61:00.0
Programming shell on device [0000:61:00.0]...
Partition file: /lib/firmware/xilinx/9964c19cdb53eb6c69b6fd2072401583/partition.xsabin
XRT build version: 2.13.0
Build hash: 37f368eae34cb70b8c3dc1c840d02e59b2b6b8cb
Build date: 2021-12-22 13:23:51
Git branch: fix-ref-error-XclBinClassCxx
PID: 26232
UID: 0
[Wed Dec 29 14:09:05 2021 GMT]
HOST: noether
EXE: /opt/xilinx/xrt/bin/unwrapped/xbmgmt2
[XBMGMT] ERROR: Write plp to icap subdev failed: Invalid argument
[xbmgmt] ERROR: Failed to write /sys/bus/pci/devices/0000:61:00.0//rp_program: Invalid argument
```

I'm actually on the latest branch from PR #6092.

I also submitted a [support request](https://support.xilinx.com/s/question/0D52E00006uVLA2SAO/u55n-flashing-the-shell-partition-doesnt-work?language=en_US). Please have a look for more info.

**Comment by uday610** [comment]
The help was provided in the support request thread!! If you still has issue please reply the support request thread in support.xilinx.com .... So I am closing this thread.
