### ISSUE TITLE
XRT headers depend on boost, but xrt_<version>-amd64-xrt.deb does not require libboost-dev

### ISSUE THREAD

**Issue by mgehre-amd** [Xilinx/XRT#6295]
I installed the xrt deb package `xrt_202210.2.13.0_18.04-amd64-xrt.deb`  on Ubuntu 18.04.
Building a host application with `g++ main.cpp -o main.o -I/opt/xilinx/xrt/include -c`
results in
```
In file included from /opt/xilinx/xrt/include/xrt/xrt_device.h:27:0,
                 from main.cpp:23:
/opt/xilinx/xrt/include/xrt/detail/any.h:21:11: fatal error: boost/any.hpp: No such file or directory
 # include <boost/any.hpp>
           ^~~~~~~~~~~~~~~
compilation terminated.
```
This can be fixed by `apt install libboost-dev`, or more specifically `apt install libboost1.65-dev`.

Can the `xrt_<version>-amd64-xrt.deb` please depend on `libboost1.65-dev` so users automatically have all they need after installing xrt?

**Comment by stsoe** [comment]
We have move to C++17 where std::any is used instead, exactly to avoid the boost package dependency. Please use -std=c++17.  https://github.com/Xilinx/XRT/pull/6156
