### ISSUE TITLE
Tests script board.sh out of date with xbutil

### ISSUE THREAD

**Issue by HFTrader** [Xilinx/XRT#6383]
XRT version: 1.23.0  e98799314cbb15e3b174ab0f8b7ba66587d0412e
Alveo u50 xilinx_u50_gen3x16_xdma_201920_3  F465B0A3-AE8C-64F6-19BC-150384ACE69B
[xbutil_query.txt](https://github.com/Xilinx/XRT/files/8214818/xbutil_query.txt)
[xbmgmt_scan.txt](https://github.com/Xilinx/XRT/files/8214819/xbmgmt_scan.txt)
[dmesg.txt](https://github.com/Xilinx/XRT/files/8214820/dmesg.txt)

I have compiled XRT/master and following the [test procedure](https://xilinx.github.io/XRT/master/html/test.html) I attempted to run the test script
```bash
mkdir tests
cd tests
<path>/XRT/build/board.sh -board u50 -sync
```
However it seems that the script expects the old version of the tools (legacy). For once, it calls `xbutil scan` and greps for the result to find the device number. 
```bash
...
export DSA=`${XILINX_XRT}/bin/xbutil scan | grep '\[0\]' | cut -d':' -f5 | cut -d'(' -f1`
```
I tried adding the `--legacy` option after `xbutil scan` but then the DSA comes empty as the grepping also seems to be off. 
I replaced the line with just `export DSA=0000:4b:00.1` but other problems occured and I gave up.

**Comment by stsoe** [comment]
board.sh is not supported or maintained.

**Comment by HFTrader** [comment]
Soren, understood.
But this script is explicitly mentioned in the documentation - in master!

https://xilinx.github.io/XRT/master/html/test.html

**Comment by stsoe** [comment]
> But this script is explicitly mentioned in the documentation - in master!
> 
> https://xilinx.github.io/XRT/master/html/test.html

@HFTrader Thanks for pointing that out, we will have to update the documentation, + @uday610 
I still use the script, just not for harvesting, which has been broken ever since internal test repos where re-organized.
I have not had the time or energy to update the script.
