### ISSUE TITLE
P2P between FPGA and GPU

### ISSUE THREAD

**Issue by hecmay** [Xilinx/XRT#6618]
XRT provides some examples for FPGA-to-FPGA or SSD-to-FPGA P2P communication:
https://xilinx.github.io/XRT/master/html/p2p.html

is it possible to do GPU-FPGA P2P communication?

**Comment by uday610** [comment]
Hello, 

[ Disclaimer: We don't have any official document/flow for this as of now. You can try on your own, but you may face issues that cannot be helped] 

You can use XRT P2P feature to do FPGA to GPU (or GPU to FPGA) p2p communication. You can let GPU read/write directly from/to the Pcie Bar using the mapped pointer of p2p buffer with GPU Memcpy APIs.
