### ISSUE TITLE
Don't have trailing colon in LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by timsnyder-siv** [Xilinx/XRT#6738]
https://github.com/Xilinx/XRT/blob/d145cb9801709fed3f3f1aac1d9a3528996e4d72/src/runtime_src/tools/scripts/install.sh#L360

setup.sh (above) will include a trailing colon in LD_LIBRARY_PATH if it is unset before sourcing setup.sh.  setup.csh does not suffer from this problem, it looks to see if LD_LIBRARY_PATH is already set and appropriately includes a delimiter if it is or sets a single value if it isn't.

With the trailing colon, code like https://github.com/buildroot/buildroot/blob/1fcdfbfb8a28b81283575efc3faa92ce4a0d4e56/support/dependencies/dependencies.sh#L15-L21 has issues that are solved by manually removing the trailing colon from LD_LIBRARY_PATH.

Please make setup.sh behave the same way as setup.csh.

**Comment by stsoe** [comment]
@timsnyder-siv Thanks,  we will fix.
