### ISSUE TITLE
[XRT] No device found 

### ISSUE THREAD

**Issue by nrllhclb** [Xilinx/XRT#6796]
Hello everyone,

I followed steps which is example of vitis-ai for zcu104, however all steps passed until putting the sdcard to the board.

In **version 2020.2** https://github.com/Xilinx/Vitis-Tutorials/blob/2020.2/Vitis_Platform_Creation/Introduction/02-Edge-AI-ZCU104/step4.md, 

When the step 2 of test 2 have been run the code as `./vadd binary_container_1.xclbin`, i would get following error on board interface console

```
[XRT] ERROR: No device found
Error: Unable to find Target Device [XRT] ERROR: device is nullptr
```

thanks for answer

**Comment by uday610** [comment]
.Thanks @bryanloz-xilinx , closing this
