### ISSUE TITLE
Why force Windows users to statically link Boost?

### ISSUE THREAD

**Issue by bryanloz-xilinx** [Xilinx/XRT#6929]
https://github.com/Xilinx/XRT/blob/d5e0350aab9fab5ffbc9d76ba74862818e219d24/src/CMake/nativeWin.cmake#L28

The choice to dynamically link or statically link Boost should remain with the person building the software. We shouldn't be forcing this imo.

**Comment by uday610** [comment]
@bryanloz-xilinx , can you please file CR regarding this
