### ISSUE TITLE
Add build id with git hash (and timestamp) to every build

### ISSUE THREAD

**Issue by sonals** [Xilinx/XRT#73]
Every time git hash changes we should embed git hash (and timestamp) into all our binaries:

xbutil (xbsak)
xbflash
libxrtcore.so
libxilinxopencl.so
HAL libs

The utilities should display the build id when they start.
The libraries could return the build id as part of an API.

**Comment by uday610** [comment]
@sonals , is this still an issue?

**Comment by stsoe** [comment]
No longer relevant.  version.h has information.
