### ISSUE TITLE
Sourcing setup.sh fails when using zsh

### ISSUE THREAD

**Issue by mgehre-amd** [Xilinx/XRT#7366]
Sourcing setup.sh [0] fails (`dirname: missing operand`) when using zsh as shell; also sourcing setup.csh doesn't work (`/opt/xilinx/xrt/setup.csh:17: bad pattern: path=(/usr/sbin ...`)

Please consider providing a setup.zsh script for zsh users. It can be almost the same as the setup.sh script, just replacing
```
XILINX_XRT=$(readlink -f $(dirname ${BASH_SOURCE[0]}))
```
by
```
XILINX_XRT=$(readlink -f $(dirname ${(%):-%N}))
```
Thanks!

[0] https://github.com/Xilinx/XRT/blob/master/src/runtime_src/tools/scripts/setup.sh

**Comment by keryell** [comment]
Can you send a PR so at least it is tested by the CI?
