### ISSUE TITLE
xbutil examine: no devices present

### ISSUE THREAD

**Issue by hoosierEE** [Xilinx/XRT#7586]
I'm trying to set up a U250 in a workstation for the first time, and got to this issue. It seems like there is no device found by xbutil examine, but based on the troubleshooting docs it seems like my card _is_ in fact recognized (by both `lspci` and Vivado's hardware manager). According to [this doc](https://xilinx.github.io/Alveo-Cards/master/debugging/build/html/docs/common-steps.html#vivado-hw-manager) the next step seems to be to "revert the card back to the golden image", but this is a brand-new card that's never been programmed by me. Is "revert" necessary?

```shell
sudo /opt/xilinx/xrt/bin/xbutil examine
System Configuration
  OS Name              : Linux
  Release              : 5.19.0-43-generic
  Version              : #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2
  Machine              : x86_64
  CPU Cores            : 18
  Memory               : 64012 MB
  Distribution         : Ubuntu 22.04.2 LTS
  GLIBC                : 2.35
  Model                : X299 UD4

XRT
  Version              : 2.14.354
  Branch               : 2022.2
  Hash                 : 43926231f7183688add2dccfd391b36a1f000bea
  Hash Date            : 2022-10-08 09:49:53
  XOCL                 : unknown, unknown
  XCLMGMT              : unknown, unknown
WARNING: xclmgmt version is unknown. Is xclmgmt driver loaded? Or is MSD/MPD running?

Devices present
  0 devices found
BDF  :  Shell  Platform UUID  Device ID  Device Ready*  
--------------------------------------------------------


* Devices that are not ready will have reduced functionality when using XRT tools
```

Running `lspci` looks like the card *is* found, but conspicuously absent are kernel drivers:

```shell
sudo lspci -vd 10ee:
17:00.0 Processing accelerators: Xilinx Corporation Device d004
	Subsystem: Xilinx Corporation Device 000e
	Flags: fast devsel, IRQ 11, NUMA node 0
	Memory at b2000000 (32-bit, non-prefetchable) [disabled] [size=32M]
	Memory at b4000000 (32-bit, non-prefetchable) [disabled] [size=64K]
	Capabilities: [40] Power Management version 3
	Capabilities: [48] MSI: Enable- Count=1/1 Maskable- 64bit+
	Capabilities: [70] Express Endpoint, MSI 00
	Capabilities: [100] Advanced Error Reporting
	Capabilities: [1c0] Secondary PCI Express
	Capabilities: [400] Access Control Services
```

My Vivado hardware manager is able to find the U250.

I'm using Vitis 2022.2 on Ubuntu 2022.04.2 LTS.

**Comment by uday610** [comment]
@hoosierEE , it is not clear, but it is showing driver is not there. Was XRT installed correctly? 

By the way, if you go to the Xilinx community forum or Alveo Forum for these type of issues, there you can probably get other similar questions/answers or quicker support.

**Comment by uday610** [comment]
Maybe you also want to review the tested operating system and try there

https://support.xilinx.com/s/article/000035189?language=en_US
https://support.xilinx.com/s/article/000034458?language=en_US

**Comment by hoosierEE** [comment]
Thanks for the response. I am using Ubuntu 22.04 LTS and the .deb file I downloaded from Xilinx (following the prompts to get the right version) is `xrt_202220.2.14.354_22.04-amd64-xrt.deb`, which I assume is XRT 2022.2, which is one of the "tested" combinations from here: https://support.xilinx.com/s/article/000034458?language=en_US. 

When I follow the install instructions (from here: https://xilinx.github.io/XRT/master/html/install.html), there is no indication of any error:

```
sudo apt install ./xrt_202220.2.14.354_22.04-amd64-xrt.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'xrt' instead of './xrt_202220.2.14.354_22.04-amd64-xrt.deb'
xrt is already the newest version (2.14.354).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Since I did this step already, it now just says "xrt is already the newest version". `apt info` says this about the `xrt` package:

```
apt info xrt
Package: xrt
Version: 2.14.354
Status: install ok installed
Priority: optional
Section: devel
Maintainer: sonal.santan@xilinx.com
Installed-Size: 104 MB
Depends: ocl-icd-libopencl1 (>= 2.2.0), lsb-release, dkms (>= 2.2.0), udev, python3, ocl-icd-opencl-dev (>= 2.2.0), uuid-dev (>= 2.27.1), libboost-filesystem1.74.0 (>= 1.74.0), libboost-program-options1.74.0 (>= 1.74.0), libc6 (>= 2.34), libgcc-s1 (>= 3.4), libprotobuf23 (>= 3.12.4), libssl3 (>= 3.0.0~~alpha1), libstdc++6 (>= 12), libudev1 (>= 183), libuuid1 (>= 2.16), ocl-icd-libopencl1 | libopencl-1.1-1 | libopencl1, ocl-icd-libopencl1 | libopencl1, ocl-icd-libopencl1 (>= 1.0) | libopencl-1.2-1
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: Xilinx RunTime stack for use with Xilinx FPGA platforms
```

**Comment by hoosierEE** [comment]
Thanks again. It seems likely that I did not install XRT properly. A local colleague is helping me currently but if that fails I'll ask on the Alveo forum.
