### ISSUE TITLE
XRT Write/Read Buffer API | CoreDump

### ISSUE THREAD

**Issue by antonpapazyan** [Xilinx/XRT#7618]
Hey, I have one simple host code trying to transfer data from host to FPGA (Alveo U280)
I am getting an issue when specifying the large buffer size.

Here is sample code in main.
        int device_index = 0;
        size_t size_in_bytes = sizeof(int) * DATA_SIZE;
        auto device = xrt::device(device_index);
        auto uuid = device.load_xclbin(binaryFile);
        auto krnl = xrt::kernel(device, uuid, "dummy_kernel");
        auto input_buffer = xrt::bo(device, size_in_bytes, krnl.group_id(0));
        int buff_in_data[DATA_SIZE];
        for (auto i = 0; i < DATA_SIZE; ++i) {
                buff_in_data[i] = 0;
        }
        input_buffer.write(buff_in_data);
        // .....
        When the buffer DATA_SIZE is 3.000.000, the core dump error I got Segmentation fault (core dumped)
        for 1M works fine.
And here is log with GDB 
0x0000000000401ec3 in xrt::device::device (didx=0, this=0x7fffffffcd10) at src/host.cpp:100
The point is when I uncomment this code < input_buffer.write(buff_in_data) > it works.
Also, would like to mention that Buffer Map API works fine for same buffer size!

---------------------------------------------------------------------
    XRT Build Version: 2.11.634
    Build Version Branch: 2021.1
    Build Version Hash: 5ad5998d67080f00bca5bf15b3838cf35e0a7b26
    Build Version Hash Date: Tue, 8 Jun 2021 20:06:48 -0700
    Build Version Date: Wed, 09 Jun 2021 05:08:58 +0000
    XOCL: 2.11.634,5ad5998d67080f00bca5bf15b3838cf35e0a7b26
    XCLMGMT: 2.11.634,5ad5998d67080f00bca5bf15b3838cf35e0a7b26

    
    NAME="CentOS Linux"
    VERSION="7 (Core)"
    
    Xbutil query output ->
    INFO: Found total 2 card(s), 2 are usable
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
System Configuration
OS name:        Linux
Release:        3.10.0-1160.36.2.el7.x86_64
Version:        #1 SMP Wed Jul 21 11:57:15 UTC 2021
Machine:        x86_64
Model:          To Be Filled By O.E.M.
CPU cores:      64
Memory:         128693 MB
Glibc:          2.17
Distribution:   CentOS Linux 7 (Core)
Now:            Fri Jul  7 13:05:08 2023 GMT
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
XRT Information
Version:        2.11.634
Git Hash:       5ad5998d67080f00bca5bf15b3838cf35e0a7b26
Git Branch:     2021.1
Build Date:     2021-06-09 05:08:58
XOCL:           2.11.634,5ad5998d67080f00bca5bf15b3838cf35e0a7b26
XCLMGMT:        2.11.634,5ad5998d67080f00bca5bf15b3838cf35e0a7b26

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Shell                           FPGA                            IDCode
xilinx_u280_xdma_201920_3       xcu280-fsvh2892-2L-e            0x14b7d093
Vendor          Device          SubDevice       SubVendor       SerNum
0x10ee          0x500d          0x000e          0x10ee          21760201R019
DDR size        DDR count       Clock0          Clock1          Clock2
32 GB           2               300             500             450
PCIe            DMA chan(bidir) MIG Calibrated  P2P Enabled     OEM ID
GEN 3x8         2               true            false           0xa6240640(N/A)
DNA                             CPU_AFFINITY    HOST_MEM size   Max HOST_MEM
                                0-63            0 Byte          0 Byte
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
QSPI Write Protection Status
Primary: N/A
Recovery: N/A
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Temperature(C)
PCB TOP FRONT   PCB TOP REAR    PCB BTM FRONT   VCCINT TEMP
47              N/A             N/A             N/A
FPGA TEMP       TCRIT Temp      FAN Presence    FAN Speed(RPM)
55              49              A               1422
QSFP 0          QSFP 1          QSFP 2          QSFP 3
N/A             N/A             N/A             N/A
HBM TEMP
N/A
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Electrical(mV|mA)
12V PEX         12V AUX         12V PEX Current 12V AUX Current
12122           12232           1491            1588
3V3 PEX         3V3 AUX         DDR VPP BOTTOM  DDR VPP TOP
3289            3417            2500            2500
SYS 5V5         1V2 TOP         1V8 TOP         0V85
5475            1211            1801            865
MGT 0V9         12V SW          MGT VTT         1V2 BTM
901             12231           1203            1204
VCCINT VOL      VCCINT CURR     VCCINT IO VOL   VCC3V3 VOL
851             11640           N/A             N/A
3V3 PEX CURR    VCCINT IO CURR  HBM1V2 VOL      VPP2V5 VOL
N/A             N/A             N/A             N/A
VCC1V2 CURR     V12 I CURR      V12 AUX0 CURR   V12 AUX1 CURR
N/A             N/A             N/A             N/A
12V AUX1 VOL    VCCAUX VOL      VCCAUX PMC VOL  VCCRAM VOL
N/A             N/A             N/A             N/A
3V3 AUX CURR    POWER WARN      VCCINT VCU 0V9
N/A             N/A             N/A
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Card Power(W)
37
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Firewall Last Error Status
Level 0 : 0x0(GOOD)

ECC Error Status
Tag     Errors      CE Count  UE Count  CE FFA              UE FFA
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Memory Status
     Tag                 Type        Temp(C)  Base Address    Size    Mem Usage   BO count
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DMA Transfer Metrics
Chan[0].h2c:  0 Byte
Chan[0].c2h:  0 Byte
Chan[1].h2c:  0 Byte
Chan[1].c2h:  0 Byte
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Streams
     Tag         Flow ID  Route ID Status   Total (B/#)     Pending (B/#)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Xclbin UUID
00000000-0000-0000-0000-000000000000
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compute Unit Status                      Addr              Status        Usage
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO: xbutil query succeeded.

dmesg is very long if required will share in a file later.
Alveo Card : xilinx_u280_xdma_201920_3

xbmgmt scan
---------------------------------------------------------------------
Deprecation Warning:
    The given legacy sub-command and/or option has been deprecated
    to be obsoleted in the next release.
 
    Further information regarding the legacy deprecated sub-commands
    and options along with their mappings to the next generation
    sub-commands and options can be found on the Xilinx Runtime (XRT)
    documentation page:
    
    https://xilinx.github.io/XRT/master/html/xbtools_map.html

    Please update your scripts and tools to use the next generation
    sub-commands and options.
---------------------------------------------------------------------
 0000:4e:00.0 xilinx_u280_xdma_201920_3(ID=0x5e278820) mgmt(inst=19968)
 0000:4d:00.0 xilinx_u50_gen3x16_xdma_201920_3 mgmt(inst=19712)

Would be nice to receive some comment or solution,
Thanks.

**Comment by stsoe** [comment]
@antonpapazyan You are out of stack space on the system you run on.
