### ISSUE TITLE
Utils can't identify BCU 1525

### ISSUE THREAD

**Issue by trappist** [Xilinx/XRT#818]
Vendor id is `1e24:1525`. The devices appear in `lspci` on linux like so:
```
06:00.0 Co-processor: Device 1e24:1525
```

But `xbutil scan` and `xbutil list` output:
```
ERROR: No card found
```
after scanning all the `vendor` files in `/sys/bus/pci/devices` (I was able to observe with strace)

**Comment by rradjabi** [comment]
@trappist Please check that your drivers are correctly installed. 

Try `lspci -v -d 10ee:` and the two devices should show kernel modules xclmgmt and xocl in use. Also verify with `lsmod | grep xocl` and `lsmod | grep xclmgmt`. If these don't exist, please try reinstalling the RPM or DEB package you built under XRT/build/Release.

**Comment by uday610** [comment]
Closed
