### ISSUE TITLE
xbutil query may not use xclRead to read CU control regsister

### ISSUE THREAD

**Issue by stsoe** [Xilinx/XRT#831]
AXI bus is frozen during bitstream download, reading the control register at this time trips the firewall.  The CU status must be acquired through a scheduler control command.

Additionally, reading AXI-lite control register affects AP_DONE which is COR.

**Comment by maxzhen** [comment]
see http://jira.xilinx.com/browse/CR-1018181

**Comment by stsoe** [comment]
Fixed by #848
