### ISSUE TITLE
Install on 7.6 or later fails

### ISSUE THREAD

**Issue by cathalmccabe** [Xilinx/XRT#867]
If installing XRT on CentOs/RHEL 7.6, installation fails with the message: "Centos or RHEL release version must be 7.4 or later"
In src/runtime_src/tools/scripts/setup.(c)sh the check is only against 7.4 and 7.5 . If neither are detected, installation fails.
` if ( "$OSREL" !~ 7.4* && "$OSREL" !~ 7.5* ) then`

It looks like the check should be changed to allow installation to continue, or if 7.6 is not currently supported, the error message should be modified.

**Comment by maxzhen** [comment]
fixed in master.
