### ISSUE TITLE
Absolute library path in OpenCL ICD is getting in the way

### ISSUE THREAD

**Issue by maxzhen** [Xilinx/XRT#89]
Today, we have absolute library path in our OpenCL ICD entry. This is getting in the way when I was trying to debug my app. It'll always load the released version of the libs, not the one in my workspace even when I set LD_LIBRARY_PATH using run.sh correctly.

If I change the entry to just specify "libxilinxopencl.so", it will work since the LD_LIBRARY_PATH now gets control of where the lib is loaded from.

So, we probably need to revisit what we put into the ICD.

**Comment by maxzhen** [comment]
In run.sh, we can run ldd against host.exe to see if it's directly linked against libOpenCL.so. If yes, then we can check if we have absolute path in ICD. If yes, then we can warn user about this.

**Comment by keryell** [comment]
I think we have to focus on having the normal case be simple for the normal user.
A user wanting to debug XRT will be probably knowledgeable to handle debugging with the ICD, changing  `/etc/OpenCL/vendors/xilinx.icd`, play with https://github.com/intel/opencl-intercept-layer or whatever.
So what about closing this issue and considering the current state as a normal behaviour?
